### ISSUE TITLE
How do I prime in Google Colab

### ISSUE THREAD

**Issue by Flesco** [lucidrains/deep-daze#122]
I tried to add a start_image_path variable in the simplified notebook, but getting this error:
AttributeError 'Imagine' object has no attribute 'start_image_path'

**Comment by NotNANtoN** [comment]
Instead of setting the `start_image_path`of an instance of the Imagine class, feed it as an additional parameter to when you create an instance e.g. `model = Imagine("This is a test", start_image_path="hot-dog.jpg")`

**Comment by Flesco** [comment]
Ok, the error is fixed, but it's ignoring the starting picture I provided. Sorry if there's an obvious mistake I'm making, I'm a noob. This is what the code looks like right now:

```
TEXT = "test"
NUM_LAYERS = 32 #@param {type:"number"}
SAVE_EVERY =  5#@param {type:"number"}
IMAGE_WIDTH = 512 #@param {type:"number"}
SAVE_PROGRESS = True #@param {type:"boolean"}
LEARNING_RATE = 1e-5 #@param {type:"number"}
ITERATIONS = 1050 #@param {type:"number"}
START_IMAGE_PATH = '/content/test.jpg'

model = Imagine(text=TEXT, save_every=SAVE_EVERY, start_image_path=START_IMAGE_PATH)
```

**Comment by NotNANtoN** [comment]
There is only pre-training based on the starting image if the forward method of the Imagine class is used. 

Instead of your for-loop, simply call `model()`

**Comment by Flesco** [comment]
That worked, thank you!

**Comment by NotNANtoN** [comment]
Great, feel free to close this issue if you have no more questions! :)

**Comment by nathanscomputerservice** [comment]
Could you give a more beginner-friendly concrete example, or, Flesco, can you copy and paste the code you used? Thank you.

**Comment by Flesco** [comment]
@nathanscomputerservice here's the notebook with my code: https://drive.google.com/file/d/1K18m1EbWGGWVBAwIAWBjLx0ifGYCi7N2/view?usp=sharing

**Comment by nathanscomputerservice** [comment]
Thank you! When I run your code in my notebook I get... Downloading ViT-B-32.pt:   0%|          | 0.00/354M [00:00<?, ?iB/s]Setting jit to False because torch version is not 1.7.1.
Downloading ViT-B-32.pt: 100%|██████████| 354M/354M [00:09<00:00, 37.2MiB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-18a7bae8bbe8> in <module>()
      4 from deep_daze import Imagine
      5 
----> 6 model = Imagine(text="Your text", epochs=6,iterations=1000,num_layers = 16, batch_size = 16, gradient_accumulate_every=2,save_progress = True, save_every = 6, img =None, start_image_path='/content/gdrive/MyDrive/start_image.jpg', start_image_train_iters=100, save_gif=True)
      7 
      8 model()

1 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1129                 return modules[name]
   1130         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1131             type(self).__name__, name))
   1132 
   1133     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Imagine' object has no attribute 'start_image_path'

It's deep-daze 0.10.2
