### ISSUE TITLE
CUDA is not available issue

### ISSUE THREAD

**Issue by frenchbones** [lucidrains/deep-daze#173]
```
UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
```
Hello,
I have this issue when running the AI.

I have found issue #138 and I ran the one liner script and got `None`

So I've tried looking for CUDA drivers for my RTX 2080 Ti, but I didn't find anything except a package called NVIDIA CUDA Toolkit in `winget` so I ran `winget install Nvidia.CUDA` and it installed successfully but even after a restart it didn't change anything.

Has anyone got this issue too? Did anyone manage to fix it?

**Comment by PochiiBoy** [comment]
I have the same problem I keep getting this:

Setting jit to False because torch version is not 1.7.1.
c:\programdata\anaconda\lib\site-packages\torch\cuda\amp\grad_scaler.py:115: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
Starting up...
Imagining "dlkjsa" from the depths of my weights...
epochs:   0%|                                                                                   | 0/20 [00:00<?, ?it/s]c:\programdata\anaconda\lib\site-packages\torch\cuda\amp\autocast_mode.py:120: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")

This is all it says for about 30 mins freezes up then shuts down.

**Comment by PochiiBoy** [comment]
I also downloaded the toolkit and it did nothing

**Comment by frenchbones** [comment]
Alright I've found a solution and I'm posting it here for people in the future.

Torch did not install properly and so I tried getting the correct version but got an OS Error when trying to install torch
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\h_bas\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'
```

So I made a forum post on the PyTorch forums here which details a fix for file paths being too long
https://discuss.pytorch.org/t/installation-problem-oserror-errno-2/131750
