### ISSUE TITLE
create_story feature generates washed out images

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#60]
I'm seeing lots of commented out normalizations. Any reason in particular those need to be gone? I noticed this feature wasn't exactly advertised anywhere (and still isn't accessible from the cli). Does that mean it's not complete?

**Comment by NotNANtoN** [comment]
Hi! The normalizations were faulty indeed. You're right, the images look more washed-out. I think that's because it is actually correct now. Before the (unnecessary) normalization turned the images much darker and distorted the colors. That leads the image to be less washed-out and distorts the colors, but it is simply not correct (could be compared to some Instagram filter).

 I fixed the scheduling system in #61 and if you use this git head you will see much better results than before.

**Comment by NotNANtoN** [comment]
You're right, the story creation was not yet advertised by me, because I feel like it's still a bit experimental. In the new PR you can see some examples for it.
